spring: 
    profiles: 
        active:
           - dev
           
           
---
server:
  port: 8001

spring:
  profiles: dev
  application:
    name: microservicecloud-dept   #为这个服务取名，非常重要！！！！！
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: root
    dbcp2:
      min-idle: 5         #最小连接数
      initial-size: 5    #初始化连接数
      max-total: 10      #最大连接数
      max-wait-millis: 200  #等待连接最长的超时时间
      
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: cn.wxj.springcloud.entitis
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
eureka:
  client:   #客户端注册进eureka服务列表
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept8001.com
    prefer-ip-address: true
    
info:
    app.name: wxj-microservicecloud-springcloudconfig01
    company.name: www.wxj.com
    build.artifactId: $project.artifactId$
    build.version: $project.version$
    
    
---
server:
  port: 8001

spring:
  profiles: test
  application:
    name: microservicecloud-dept   #为这个服务取名，非常重要！！！！！
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB02
    username: root
    password: root
    dbcp2:
      min-idle: 5         #最小连接数
      initial-size: 5    #初始化连接数
      max-total: 10      #最大连接数
      max-wait-millis: 200  #等待连接最长的超时时间
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: cn.wxj.springcloud.entitis
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml

eureka:
  client:       #客户端注册进eureka服务列表
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept8001.com
    prefer-ip-address: true
    
info:
    app.name: wxj-microservicecloud-springcloudconfig01
    company.name: www.wxj.com
    build.artifactId: $project.artifactId$
    build.version: $project.version$